In [12]:
planet = "Bumi"
diameter = 17073533
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Bumi is 17073533 kilometers.


In [13]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
lst[3][1][2][0]
print(lst[3][1][2][0])

hello


In [14]:
s = 'Mama saya suka makan!'
s.split()

['Mama', 'saya', 'suka', 'makan!']

In [15]:
def panggil(nama):
    print('Hello '+ nama)
panggil('vava')

Hello vava


In [16]:
def perkalian(x):
    return x**2
out = perkalian(7)
print(out)

49


In [17]:
def domainGet(email):
    return email.split('@')[-1]
domainGet('vava@domainpesansik.com')

'domainpesansik.com'

In [18]:
def caught_speeding(speed, is_birthday):
    
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'
caught_speeding(31,True)

'No Ticket'

In [19]:
seq = ['sapi','kambing','ayam','angpao','kuda']
list(filter(lambda word: word[0]=='k',seq))

['kambing', 'kuda']

In [20]:
seq = [1,2,3,4,5]
ab = list(map(lambda var: var*2,seq))
print(ab)
ab = list(filter(lambda item: item%2 == 0,seq))
print(ab)

[2, 4, 6, 8, 10]
[2, 4]


In [21]:
import numpy as np

In [22]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
cb = np.arange(0,10)
bc = np.arange(0,11,2)
print(cb)
print(bc)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [25]:
cb = np.zeros((5,5))
bc = np.ones((3,3))
cd = np.linspace(0,5,10)
print(cb)
print(bc)
print(cd)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
bc = np.random.rand(2)
cd = np.random.rand(5,5)
dc= np.random.randn(5)
ae = np.random.randn(5,5)
print(bc)
print()
print(cd)
print()
print(dc)
print()
print(ae)

[0.59319757 0.94746943]

[[0.86751022 0.64356278 0.66491198 0.58572527 0.0864516 ]
 [0.12909267 0.16504562 0.30308691 0.28327377 0.15504824]
 [0.41595279 0.95638115 0.14971556 0.00801447 0.14874179]
 [0.5496435  0.53392667 0.93941082 0.22201328 0.51256167]
 [0.32285979 0.17315015 0.7730566  0.89422224 0.28518266]]

[ 0.74478615 -0.05940134  0.54389697 -1.01919476 -0.12237095]

[[ 1.37537905 -0.53501884  0.18061319  0.55414013 -0.42760107]
 [ 0.25601303 -0.16814347  0.09022435  1.0497228  -0.73397871]
 [ 1.02657368 -0.67876938  0.26197271  0.09894495  0.13917711]
 [ 0.62655641  0.57899157 -0.70329914  0.6650652   0.07311647]
 [-0.21871757  0.01256676  0.53565378 -1.98336842 -0.36898111]]


In [28]:
np.random.randint(5,20,10)

array([13, 19,  7, 14, 15, 12,  6,  5,  7, 16])

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
print()
reshaped_arr = arr.reshape((3, 4))
print(reshaped_arr)
print()
flattened_arr = reshaped_arr.reshape((12,))
print(flattened_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
arr = np.array([5, 2, 3, 4, 12, 6, 7, 8, 9, 1, 11, 12])
cb= arr.argmax()
bc = arr.argmin()
print(cb)
print()
print(bc)

4

9


In [31]:
arr = np.arange(0,15)
print(arr)
print(arr[6])
print(arr[1:5])
print(arr[0:5])
arr[0:5]=100
print(arr)
slice_of_arr = arr[0:6]
print(slice_of_arr)
slice_of_arr[:]=99
print(slice_of_arr)
print(arr)
arr_copy = arr.copy()
print(arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
6
[1 2 3 4]
[0 1 2 3 4]
[100 100 100 100 100   5   6   7   8   9  10  11  12  13  14]
[100 100 100 100 100   5]
[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10 11 12 13 14]
[99 99 99 99 99 99  6  7  8  9 10 11 12 13 14]


In [32]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
print(arr_2d)
print(arr_2d[1])
print(arr_2d[1][0])
      
# memotong array 2d
#memotong array dari pojok kanan
print(arr_2d[:2,1:])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[20 25 30]
20
[[10 15]
 [25 30]]


In [33]:
#fancy indexing
arr2d = np.zeros((10,10))
print(arr2d)
arr_length = arr2d.shape[1]
for i in range(arr_length):
    arr2d[i] = i
arr2d

arr2d[[2,4,6,8]]
arr2d[[6,4,2,7]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [34]:
#numpy operator
arr = np.arange(0,10)
print(arr)

cb = arr + arr
print(cb)

bc = arr * arr
print(bc)

cd = arr**3
print(cd)

ae = arr - arr
print(ae)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[  0   1   8  27  64 125 216 343 512 729]
[0 0 0 0 0 0 0 0 0 0]


In [35]:
#universal array function
np.sqrt(arr)
ab = np.exp(arr)
print(ab)
bc = np.sin(arr)
print(bc)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [36]:
import pandas as pd

In [43]:
#series
labels = ['vava','nia','milo']
my_list = [5,10,20]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

print(pd.Series(data=my_list))
print()
print(pd.Series(data=my_list,index=labels))
print()
ser = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])   
print(ser)

0     5
1    10
2    20
dtype: int64

vava     5
nia     10
milo    20
dtype: int64

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64


In [80]:
#dataframe
from numpy.random import randn
np.random.seed(30)
df = pd.DataFrame(randn(5,5),index='A B C D E'.split(),columns='Q W E R T'.split())
print(df)

print(df[['W', 'E']])
print(df[['W', 'E']]>0)
print(df[(df['W']>0) & (df['T'] > 1)])
result = df[df > 0]
print(result)

          Q         W         E         R         T
A -1.264053  1.527905 -0.970711  0.470560 -0.100697
B  0.303793 -1.725962  1.585095  0.134297 -1.106855
C  1.578226  0.107498 -0.764048 -0.775189  1.383847
D  0.760385 -0.285646  0.538367 -2.083897  0.937782
E -0.005778 -0.467479 -0.423015  1.064482 -2.903368
          W         E
A  1.527905 -0.970711
B -1.725962  1.585095
C  0.107498 -0.764048
D -0.285646  0.538367
E -0.467479 -0.423015
       W      E
A   True  False
B  False   True
C   True  False
D  False   True
E  False  False
          Q         W         E         R         T
C  1.578226  0.107498 -0.764048 -0.775189  1.383847
          Q         W         E         R         T
A       NaN  1.527905       NaN  0.470560       NaN
B  0.303793       NaN  1.585095  0.134297       NaN
C  1.578226  0.107498       NaN       NaN  1.383847
D  0.760385       NaN  0.538367       NaN  0.937782
E       NaN       NaN       NaN  1.064482       NaN


In [53]:
df['BARU'] = df['Q'] + df['T']
print(df)

          Q         W         E         R         T      BARU
A -1.264053  1.527905 -0.970711  0.470560 -0.100697 -1.364749
B  0.303793 -1.725962  1.585095  0.134297 -1.106855 -0.803062
C  1.578226  0.107498 -0.764048 -0.775189  1.383847  2.962073
D  0.760385 -0.285646  0.538367 -2.083897  0.937782  1.698167
E -0.005778 -0.467479 -0.423015  1.064482 -2.903368 -2.909146


In [54]:
df.drop('BARU',axis=1,inplace=True)
print(df)

          Q         W         E         R         T
A -1.264053  1.527905 -0.970711  0.470560 -0.100697
B  0.303793 -1.725962  1.585095  0.134297 -1.106855
C  1.578226  0.107498 -0.764048 -0.775189  1.383847
D  0.760385 -0.285646  0.538367 -2.083897  0.937782
E -0.005778 -0.467479 -0.423015  1.064482 -2.903368


In [57]:
print(df.loc['A'])
print(df.loc[['A','D'],['R','T']])

Q   -1.264053
W    1.527905
E   -0.970711
R    0.470560
T   -0.100697
Name: A, dtype: float64
          R         T
A  0.470560 -0.100697
D -2.083897  0.937782


In [72]:
df.reset_index()
print(df)
newind = 'CA NY WY OR CO'.split()
df['States'] = newind
print(df)

          Q         W         E         R         T
A  0.550757  0.954356  0.782777 -1.793238  1.241855
B  1.707747  0.323153 -0.991834 -1.163282 -0.021335
C -1.581995 -1.243114 -0.410169 -1.055075 -1.057312
D -1.284117  0.913126 -1.387745  0.030028 -0.450008
E  0.205633 -0.460026 -0.173413 -0.216655 -0.259935
          Q         W         E         R         T States
A  0.550757  0.954356  0.782777 -1.793238  1.241855     CA
B  1.707747  0.323153 -0.991834 -1.163282 -0.021335     NY
C -1.581995 -1.243114 -0.410169 -1.055075 -1.057312     WY
D -1.284117  0.913126 -1.387745  0.030028 -0.450008     OR
E  0.205633 -0.460026 -0.173413 -0.216655 -0.259935     CO


In [76]:
df = pd.DataFrame(randn(5,5),index='A B C D E'.split(),columns='Q W E R T'.split())
newind = 'CA NY WY OR CO'.split()
df['States'] = newind
df.set_index('States',inplace=True)
print(df)

               Q         W         E         R         T
States                                                  
CA      0.566293  0.990522 -0.594763  0.343463 -2.589323
NY     -0.016502 -0.066091 -0.128366 -0.895577  0.575098
WY     -0.498447 -1.155300  0.900839  0.878961 -1.494936
OR     -0.302494 -1.063798  1.704724  0.877426  1.002560
CO     -1.043765  1.268028 -0.282022  0.331680  0.437061


In [90]:
# multi index
kota = ['SD','SD','SD','SMP','SMA','SMA']
populasi = [1,2,3,1,2,3]
hier_index = list(zip(kota,populasi))
hier_index = pd.MultiIndex.from_tuples(hier_index)
print(hier_index)

MultiIndex([( 'SD', 1),
            ( 'SD', 2),
            ( 'SD', 3),
            ('SMP', 1),
            ('SMA', 2),
            ('SMA', 3)],
           )


In [93]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['sby','sda'])
print(df)
df.loc['SD']

            sby       sda
SD  1 -0.282022  0.331680
    2  0.437061  0.455029
    3 -0.379949  0.785928
SMP 1 -0.258533  0.932148
SMA 2 -1.390775 -0.658553
    3  0.703629 -0.961741


sby       sda
1 -0.282022  0.331680
2  0.437061  0.455029
3 -0.379949  0.785928

In [94]:
#missing data
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})
print(df)


     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3


In [95]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [96]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [102]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [103]:
df.fillna(df.mean(), inplace=True)
print(df)


     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3


In [106]:
#Groupby
data = {'SD':['UNSUR','UNSUR','SANMAR','SANMAR','PETRA','PETRA'],
       'ANAK':['vava','santi','milo','waffle','nia','molgi'],
       'umur':[8,9,6,2,8,4]}
print(data)
df = pd.DataFrame(data)
print(df)

{'SD': ['UNSUR', 'UNSUR', 'SANMAR', 'SANMAR', 'PETRA', 'PETRA'], 'ANAK': ['vava', 'santi', 'milo', 'waffle', 'nia', 'molgi'], 'umur': [8, 9, 6, 2, 8, 4]}
       SD    ANAK  umur
0   UNSUR    vava     8
1   UNSUR   santi     9
2  SANMAR    milo     6
3  SANMAR  waffle     2
4   PETRA     nia     8
5   PETRA   molgi     4


In [111]:
by = df.groupby("SD")
print(by)

In [122]:
mean_umur = df.groupby('SD')['umur'].mean()
print(mean_umur)
std = df.groupby('SD')['umur'].std()
print("std")
print(std)
min = df.groupby('SD')['umur'].min()
print("min")
print(min)
max = df.groupby('SD')['umur'].max()
print("max")
print(max)
count = df.groupby('SD')['umur'].count()
print("count")
print(count)

SD
PETRA     6.0
SANMAR    4.0
UNSUR     8.5
Name: umur, dtype: float64
std
SD
PETRA     2.828427
SANMAR    2.828427
UNSUR     0.707107
Name: umur, dtype: float64
min
SD
PETRA     4
SANMAR    2
UNSUR     8
Name: umur, dtype: int64
max
SD
PETRA     8
SANMAR    6
UNSUR     9
Name: umur, dtype: int64
count
SD
PETRA     2
SANMAR    2
UNSUR     2
Name: umur, dtype: int64


In [123]:
df.groupby('SD')['umur'].describe()

count  mean       std  min   25%  50%   75%  max
SD                                                      
PETRA     2.0   6.0  2.828427  4.0  5.00  6.0  7.00  8.0
SANMAR    2.0   4.0  2.828427  2.0  3.00  4.0  5.00  6.0
UNSUR     2.0   8.5  0.707107  8.0  8.25  8.5  8.75  9.0

In [124]:
df.groupby('SD')['umur'].describe().transpose()

SD        PETRA    SANMAR     UNSUR
count  2.000000  2.000000  2.000000
mean   6.000000  4.000000  8.500000
std    2.828427  2.828427  0.707107
min    4.000000  2.000000  8.000000
25%    5.000000  3.000000  8.250000
50%    6.000000  4.000000  8.500000
75%    7.000000  5.000000  8.750000
max    8.000000  6.000000  9.000000

In [125]:
#merge, joining, concatenating

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

print (df1)
print (df2)
print (df3)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7
      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11


In [126]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [127]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [129]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})
print(left)
print(right)
pd.merge(left, right, on=['key1', 'key2'])

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3
  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3


key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [131]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])
print(left)
print(right)
left.join(right)

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3


A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [132]:
#operasi
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [133]:
cd = df['col2'].unique()
dc= df['col2'].value_counts()
print(cd)
print(dc)

[444 555 666]
col2
444    2
555    1
666    1
Name: count, dtype: int64


In [134]:
def times2(x):
    return x*2
cd = df['col1'].apply(times2)
dc = df['col3'].apply(len) 
ef = df['col1'].sum()
fe = df.sort_values(by='col2')
print(cd)
print(dc)
print(ef)
print(fe)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64
0    3
1    3
2    3
3    3
Name: col3, dtype: int64
10
   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi


In [6]:
#input output
import numpy as np
import pandas as pd
df = pd.read_csv('example')
print(df)


    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
